<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-KMOGL3M" failures="3" tests="32" name="create.CreatePageTests" time="1048.511" errors="0" timestamp="2024-12-11T13:15:07 IST" skipped="0">
  <testcase classname="create.CreatePageTests" name="CertAndLogin" time="7.866"/>
  <testcase classname="create.CreatePageTests" name="ClickOnCreateReource" time="1.724"/>
  <testcase classname="create.CreatePageTests" name="TestLocationDropdown" time="0.485"/>
  <testcase classname="create.CreatePageTests" name="TestProjectNameDropdown" time="0.634"/>
  <testcase classname="create.CreatePageTests" name="TestStoragePathDropdown" time="0.553"/>
  <testcase classname="create.CreatePageTests" name="TestOSDropdown" time="0.959"/>
  <testcase classname="create.CreatePageTests" name="TestIOPSDropdown" time="0.324"/>
  <testcase classname="create.CreatePageTests" name="TestHorizontalSwitchOn" time="0.149"/>
  <testcase classname="create.CreatePageTests" name="TestLowerThreshold" time="0.284"/>
  <testcase classname="create.CreatePageTests" name="TestUpperThreshold" time="0.350"/>
  <testcase classname="create.CreatePageTests" name="TestVcpuForHorizontalScaling" time="0.257"/>
  <testcase classname="create.CreatePageTests" name="TestRAMForhorizontalScaling" time="0.191"/>
  <testcase classname="create.CreatePageTests" name="TestDiskForHorizontalScaling" time="1.048"/>
  <testcase classname="create.CreatePageTests" name="TestLoadBalancerOn" time="0.535"/>
  <testcase classname="create.CreatePageTests" name="TestTemplateCheckBoxChecked" time="0.565"/>
  <testcase classname="create.CreatePageTests" name="TestMaxGroupCount" time="1.305"/>
  <testcase classname="create.CreatePageTests" name="TestVMBackupSwitchOn" time="0.584"/>
  <testcase classname="create.CreatePageTests" name="TestBackUpFrequencyDropdown" time="0.305"/>
  <testcase classname="create.CreatePageTests" name="TestRetentionPeriodDropdown" time="0.296"/>
  <testcase classname="create.CreatePageTests" name="TestSIEMSwitchOn" time="0.582"/>
  <testcase classname="create.CreatePageTests" name="TestSIEMDropdown" time="0.274"/>
  <testcase classname="create.CreatePageTests" name="TestVLANDropdown" time="1.440"/>
  <testcase classname="create.CreatePageTests" name="TestVMNameTextBoxForHorizontal" time="0.209"/>
  <testcase classname="create.CreatePageTests" name="TestAssignRemoteUserButton" time="3.683"/>
  <testcase classname="create.CreatePageTests" name="TestAssignRemoteUserModal" time="0.405"/>
  <testcase classname="create.CreatePageTests" name="TestAssignRemoteUserModal" time="0.195"/>
  <testcase classname="create.CreatePageTests" name="TestAssignRemoteUserModal" time="0.468"/>
  <testcase classname="create.CreatePageTests" name="TestSaveRolesButtonInAssignRolesModal" time="0.039"/>
  <testcase classname="create.CreatePageTests" name="TestCreateButtontocheckErrorsInTheForm" time="0.080">
    <failure message="No Errors Found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Errors Found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at create.CreatePageTests.TestCreateButtontocheckErrorsInTheForm(CreatePageTests.java:864)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TestCreateButtontocheckErrorsInTheForm -->
  <testcase classname="create.CreatePageTests" name="TestCreateButtontocheckErrorsAfterSubmit" time="6.022">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at create.CreatePageTests.TestCreateButtontocheckErrorsAfterSubmit(CreatePageTests.java:882)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TestCreateButtontocheckErrorsAfterSubmit -->
  <testcase classname="create.CreatePageTests" name="TestCreateButtontocheckSuccessMessageAfterSubmit" time="0.090"/>
  <testcase classname="create.CreatePageTests" name="TestIPAddress" time="1016.610">
    <failure message="IP is not pinging for the vm  expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: IP is not pinging for the vm  expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at create.CreatePageTests.TestIPAddress(CreatePageTests.java:967)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TestIPAddress -->
</testsuite> <!-- create.CreatePageTests -->
